### ISSUE TITLE
Allow web lab style variable annotations to be defined and exported to CellML

### ISSUE THREAD

**Issue by MichaelClerx** [MichaelClerx/myokit#16]
CellML: When importing/exporting change CellML attributes into Myokit meta-data and vice-versa.

**Comment by MichaelClerx** [comment]
In particular, for the web lab we need this kind of annotation:

```
<rdf:RDF
        xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
        xmlns:bqbiol="http://biomodels.net/biology-qualifiers/"
        xmlns:oxmeta="https://chaste.comlab.ox.ac.uk/cellml/ns/oxford-metadata#"
        xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#">
    <rdf:Description rdf:about="#engine_time">
        <bqbiol:is rdf:resource="https://chaste.comlab.ox.ac.uk/cellml/ns/oxford-metadata#time"/>
    </rdf:Description>
</rdf>
```

Not sure what this would look like in Myokit! Might be easiest to hack it into the CellML export for now?

```
[engine]
time = 0
    weblab: time
```

**Comment by MichaelClerx** [comment]
@jonc125 would CellML 2.0 annotations look essentially the same, except live outside of the model?

**Comment by jonc125** [comment]
Indeed. Although could also live inside the model file.
