### ISSUE TITLE
Windows easy installation cannot create shortcut to Start Menu

### ISSUE THREAD

**Issue by chonlei** [MichaelClerx/myokit#180]
Following the 2-step easy installation on http://myokit.org/windows, using 
- WinPython 2.7.10.3
- Myokit 1.26.3 installer for WinPython (64 bit)

After the installation (with 'completed'), it does not create a shortcut to the Windows Start Menu. I ran it on a Windows 10 laptop.

**Comment by MichaelClerx** [comment]
https://www.blog.pythonlibrary.org/2010/01/23/using-python-to-create-shortcuts/

**Comment by MichaelClerx** [comment]
https://conda.io/docs/user-guide/tasks/build-packages/add-win-start-menu-items.html

**Comment by MichaelClerx** [comment]
Hi @chonlei 
This is now no longer handled by the installer, but via `myokit icons`

**Comment by chonlei** [comment]
Thanks!
