### ISSUE TITLE
Error message: TypeError: must be char, not unicode

### ISSUE THREAD

**Issue by mirams** [MichaelClerx/myokit#225]
I am getting the following on MacOSX Python 2.7.10:

    Traceback (most recent call last):
      File "cmaesfit.py", line 86, in <module>
        log = myokit.DataLog.load_csv(data_file).npview()
      File "/Library/Python/2.7/site-packages/myokit/_datalog.py", line 717, in load_csv
        x = array.array(typecode)
    TypeError: must be char, not unicode

But it doesn't happen on linux Python 2.7.12

**Comment by MichaelClerx** [comment]
Seems to be Python 2.7.10 rather than OS/X related. Already fixed an instance of this bug once here: https://github.com/MichaelClerx/myokit/blob/v1.27.6/myokit/_datalog.py#L1584-L1586

Now implementing fix in other locations too...

**Comment by MichaelClerx** [comment]
Added travis testing for Python 2.7.10 (on linux) which recreates this issue.
