### ISSUE TITLE
Fix Mac OS/X installation instruction at http://myokit.org/osx

### ISSUE THREAD

**Issue by teosbpl** [MichaelClerx/myokit#249]
The documentation says: http://myokit.org/osx
To install Myokit, run:
_pip install myokit_

it should be 
_pip install git+https://github.com/MichaelClerx/myokit.git_
otherwise an error "Pip install cannot unpack..." is launched as git is not a pip repo itself.

**Comment by teosbpl** [comment]
Btw: after that a non-OpenCL part of Myokit works OK.

**Comment by MichaelClerx** [comment]
Thanks for testing!

Bit confused though. Just `pip install myokit` should install Myokit from Pypi https://pypi.org/project/myokit/  Is that not working for you?
