### ISSUE TITLE
Make Myokit with work Python 2 and 3

### ISSUE THREAD

**Issue by MichaelClerx** [MichaelClerx/myokit#26]
Advantages:

- Python3 is better than Python2
- WinPython and a few others have stopped releasing Python2 builds
- Fedora and Ubuntu are moving to make Python3 the default in 2016 (they didn't)
- Myokit will be more stable for the future

Disadvantages:
- ~Some servers/clusters might not support Python3? This would mean they are at least 8+ years old if it technically can't be done, or about 5+ years old if users don't have the permissions to do it.~

~Packages without Python3 support:~
- ~Mayavi (due to VTK and envisage)~
  ~See: https://github.com/enthought/mayavi/issues/84~
  ~See: https://github.com/enthought/mayavi/pull/250~
- ~Entought Canopy (due to Mayavi/VTK)~
  ~See: https://support.enthought.com/hc/en-us/articles/204469600~

**Comment by MichaelClerx** [comment]
Changed title, because still too early to drop Python2 altogether!

**Comment by teosbpl** [comment]
Great source http://python-future.org/compatible_idioms.html

**Comment by teosbpl** [comment]
Stuck with class Unit member method: __truediv__ which is stuck in an endless loop in Python3.
Not sure about the intention, maybe it would be better to call some function directly?
Check out https://github.com/teosbpl/myokit/tree/feature/Python3compatibilityIssues and call python3 setup.py install to see it in action.

**Comment by teosbpl** [comment]
Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    from myokit import VERSION as version
  File "/home/teos/data/projects/elfizjo_lab/HH/myokit/myokit/__init__.py", line 288, in <module>
    from myokit import units # Also loads all common unit names
  File "/home/teos/data/projects/elfizjo_lab/HH/myokit/myokit/units.py", line 61, in <module>
    _add('N', kg * m / s**2, quantifiable=True, output=True)
  File "/home/teos/data/projects/elfizjo_lab/HH/myokit/myokit/_expr.py", line 2978, in __truediv__
    return self / other
  File "/home/teos/data/projects/elfizjo_lab/HH/myokit/myokit/_expr.py", line 2978, in __truediv__
    return self / other
  File "/home/teos/data/projects/elfizjo_lab/HH/myokit/myokit/_expr.py", line 2978, in __truediv__
    return self / other
  File "/home/teos/data/projects/elfizjo_lab/HH/myokit/myokit/_expr.py", line 2978, in __truediv__
    return self / other
  File "/home/teos/data/projects/elfizjo_lab/HH/myokit/myokit/_expr.py", line 2978, in __truediv__
    return self / other
  File "/home/teos/data/projects/elfizjo_lab/HH/myokit/myokit/_expr.py", line 2978, in __truediv__
    return self / other
  File "/home/teos/data/projects/elfizjo_lab/HH/myokit/myokit/_expr.py", line 2978, in __truediv__
    return self / other
...

**Comment by teosbpl** [comment]
return self.__div__(other) seems to work at first glance.

**Comment by MichaelClerx** [comment]
Thanks!

I've started updating a lot of the Python2 code (#61 #82 #85 #77) so we can do things more gradually and test for a while before making the transition.

**Comment by MichaelClerx** [comment]
Current status:

```
Ran 497 tests in 9.024s

FAILED (failures=8, errors=110)
```

**Comment by MichaelClerx** [comment]
```
Ran 512 tests in 32.030s

FAILED (failures=8, errors=88)
```

**Comment by MichaelClerx** [comment]
```
Ran 512 tests in 53.324s

FAILED (failures=8, errors=72)
```

**Comment by MichaelClerx** [comment]
```
Ran 512 tests in 60.189s

FAILED (failures=8, errors=70)

```

**Comment by MichaelClerx** [comment]
```
Ran 512 tests in 66.085s

FAILED (failures=2, errors=59)
```

**Comment by MichaelClerx** [comment]
```
Ran 512 tests in 63.472s

FAILED (failures=2, errors=49)
```

**Comment by MichaelClerx** [comment]
- [ ] test_aux.py
- [ ] test_config.py
- [ ] test_cvode_simulation.py
- [ ] test_datablock.py
- [ ] test_datalog.py
- [ ] test_dependency_checking.py
- [ ] test_expressions.py
- [ ] test_formats.py
- [ ] test_formats_axon.py
- [ ] test_formats_cellml.py
- [ ] test_formats_channelml.py
- [ ] test_formats_exporters.py
- [ ] test_formats_expression_writers.py
- [ ] test_formats_importers.py
- [ ] test_formats_mathml.py
- [ ] test_formats_sympy.py
- [ ] test_formats_wcp.py
- [ ] test_ic_simulation.py
- [ ] test_jacobian_calculator.py
- [ ] test_jacobian_tracer.py
- [ ] test_lib_common.py
- [ ] test_lib_deps.py
- [ ] test_lib_fit.py
- [ ] test_lib_markov.py
- [ ] test_lib_multi.py
- [ ] test_lib_plots.py
- [ ] test_loadsave.py
- [ ] test_meta.py
- [ ] test_model_api.py
- [ ] test_mxml.py
- [ ] test_pacing_factory.py
- [ ] test_parser.py
- [ ] test_progress_printer.py
- [ ] test_protocol_and_pacing.py
- [ ] test_p_simulation.py
- [ ] test_pype.py
- [ ] test_rhs_benchmarker.py
- [ ] test_simulation_1d.py
- [ ] test_simulation_log_interval.py
- [ ] test_simulation_opencl.py
- [ ] test_simulation_opencl_log_interval.py
- [ ] test_units_and_quantities.py

**Comment by MichaelClerx** [comment]
- [ ] test_formats.py
- [ ] test_formats_axon.py
- [ ] test_formats_cellml.py
- [ ] test_formats_channelml.py
- [ ] test_formats_exporters.py
- [ ] test_formats_expression_writers.py
- [ ] test_formats_importers.py
- [ ] test_formats_mathml.py
- [ ] test_formats_sympy.py
- [ ] test_formats_wcp.py

**Comment by MichaelClerx** [comment]
- [ ] test_ic_simulation.py
- [ ] test_jacobian_calculator.py
- [ ] test_jacobian_tracer.py
- [ ] test_lib_common.py
- [ ] test_lib_deps.py
- [ ] test_lib_fit.py
- [ ] test_lib_markov.py
- [ ] test_lib_multi.py
- [ ] test_lib_plots.py

**Comment by MichaelClerx** [comment]
- [ ] test_loadsave.py
- [ ] test_meta.py
- [ ] test_model_api.py
- [ ] test_mxml.py
- [ ] test_pacing_factory.py
- [ ] test_parser.py
- [ ] test_progress_printer.py
- [ ] test_protocol_and_pacing.py

**Comment by MichaelClerx** [comment]
- [ ] test_p_simulation.py
- [ ] test_pype.py
- [ ] test_rhs_benchmarker.py
- [ ] test_simulation_1d.py
- [ ] test_simulation_log_interval.py
- [ ] test_simulation_opencl.py
- [ ] test_simulation_opencl_log_interval.py
- [ ] test_units_and_quantities.py

**Comment by MichaelClerx** [comment]
```
Ran 512 tests in 66.245s

FAILED (failures=2, errors=30)
```

**Comment by MichaelClerx** [comment]
```
Ran 512 tests in 64.213s

FAILED (failures=1, errors=26)
```

**Comment by MichaelClerx** [comment]
```
Ran 512 tests in 70.133s

FAILED (failures=1, errors=14)
```

**Comment by MichaelClerx** [comment]
```
Ran 519 tests in 77.662s

OK
```
Still some warnings

**Comment by MichaelClerx** [comment]
Two last errors on 3.4 and 3.5

**Comment by MichaelClerx** [comment]
Have checked all the commands. Seems fine. Now starting long testing by using phase :-)
