### ISSUE TITLE
Analytical HH simulations with non-V dependent alpha and beta

### ISSUE THREAD

**Issue by DGWhittaker** [MichaelClerx/myokit#387]
Would be good to enable analytical HH simulations with _alpha_ and _beta_ which do not depend on membrane potential (but may depend on other things such as drug concentration). When I tried doing this, I got the following error:
`myokit.lib.hh.HHModelError: State ikr.b must have "inf-tau form" or "alpha-beta form". See myokit.lib.hh.has_inf_tau_form() and myokit.lib.hh.has_alpha_beta_form().`
despite writing _b_ in terms of _inf_ and _tau_. I'm guessing this is because they don't depend on _V_.
Thanks!

**Comment by MichaelClerx** [comment]
Thanks @DGWhittaker , I'll look into this shortly.

I think you're right: The HHModel class first converts alpha/beta forms to inf/tau forms:

https://github.com/MichaelClerx/myokit/blob/master/myokit/lib/hh.py#L118

and then checks if all states are in inf/tau form:

https://github.com/MichaelClerx/myokit/blob/master/myokit/lib/hh.py#L214-L222

Both these checks currently include a check for dependence on V. I think I can drop that without any ramifications... Will check!

**Comment by MichaelClerx** [comment]
Meanwhile, could you post (all or part of) an example model? Just the state with its V-independent  alpha and beta would be fine!

**Comment by DGWhittaker** [comment]
Here's an example model. It's written in a slightly weird way from when I
was optimising kon/koff, but should work anyway (except for analytical
simulations)!

Cheers

**Comment by MichaelClerx** [comment]
Cheers! Did you email it to github or something? Not showing up unfortunately :D
