### ISSUE TITLE
Progress  output from CVODE is captured by SubCapture

### ISSUE THREAD

**Issue by MichaelClerx** [MichaelClerx/myokit#43]
In CVODE simulations, the progress printer output is currently captured by
SubCapture. Fix this!

**Comment by MichaelClerx** [comment]
Maybe stop using the subcapture wrapped around sim at all? Not sure what it's meant to catch...

**Comment by MichaelClerx** [comment]
Have stopped wrapping, and now handling CVODE warnings in a better way, all in #595

**Comment by MichaelClerx** [comment]
Hi @martinjrobins !
I was having issues with capturing sim output myself, so I've rewritten now to avoid the capturing.
The new capture-free `Simulation` class is available in `master` now, but not yet released as it makes a switch from CVODE to CVODES which is a rather big chance I want to test a bit longer in practice before doing a new pip release

**Comment by martinjrobins** [comment]
fantastic :) Thanks @MichaelClerx, let me know when it gets released and I'll update our pinned myokit dependency
