### ISSUE TITLE
Simulations: Deprecate `pre()` and the default state?

### ISSUE THREAD

**Issue by MichaelClerx** [MichaelClerx/myokit#637]
At the moment, simulations have

- a state
- a time
- a default state

a method `run()` which

- updates the time
- updates the state

a method `pre()` which

- updates the state
- updates the default state

a method `reset()` which

- sets the state to the default state
- sets time to 0

In addition things are gettable/settable via `state()`, `set_state()`, `default_state()`, and `set_default_state()`.

This made sense at the time, but has been causing confusion in complex use cases, as it requires the user to remember that the simulation has 2 internal states.

So I'm wondering whether to remove `pre`, `reset`, the default state, and its methods?

**Comment by MichaelClerx** [comment]
Make casual use a bit trickier:
```
sim.pre(100 * cl)
log = sim.run(cl)
```
becomes
```
sim.run(100 * cl, log=myokit.LOG_NONE)
sim.set_time(0)
log = sim.run(cl)
```

And:
```
sim.pre(100 * cl)
log = sim.run(cl)
sim.reset()
```
becomes
```
sim.run(100 * cl, log=myokit.LOG_NONE)
sim.set_time(0)
state = sim.state()
log = sim.run(cl)
sim.set_state(state)
sim.set_time(0)
```

But more complex usage would be simplified, as there's only 1 internal state to think about.

**Comment by ordogb** [comment]
Hi Michael, What I do with Myokit qualifies as simple (simplest?) use. I have used pre() and reset() extensively, but hadn`t you implemented them I could have just as well used state(). So don`t worry, do what is best for the project on the long run! But thanks for asking!

**Comment by MichaelClerx** [comment]
Going to leave it in for now
