### ISSUE TITLE
Make Myokit work with sundials 2.x and 3.x

### ISSUE THREAD

**Issue by MichaelClerx** [MichaelClerx/myokit#65]
Find out a way to make Myokit work with sundials 2 and sundials 3 (e.g. the cvode_dense.h include has changed).

So far (feb 2018) Ubuntu and Fedora both ship 2.x (and not the newest releases either)

See e.g. https://chaste.cs.ox.ac.uk/trac/changeset/04c367eed610358fe42f8ba97355ada2b84b131b/git_repo

**Comment by teosbpl** [comment]
Do you have an idea where sundials version string should be placed? It should probably be set automagically by checking library version. Do you know any automagical mechanism for checking version in Python?
It can also be verified by compiling and linking a test source against this library and checking which version fails.
Let me know which version would you prefer.

**Comment by MichaelClerx** [comment]
I think for now an option in myokit.ini (default 2) should be fine. If it becomes common to have 3 installed we can look into doing something more clever...

**Comment by teosbpl** [comment]
SUNLinSolFree and SUNMatDestroy could probably be called on exit to free memory of both objects before destroying object in sim.c and cvode.c (?)

**Comment by teosbpl** [comment]
Verify if this can be closed.

**Comment by MichaelClerx** [comment]
Still need to test this, but will get round to it soon!

Seems [Fedora 28](https://en.wikipedia.org/wiki/Fedora_(operating_system)#Releases) will [ship sundials 3.1.0](https://apps.fedoraproject.org/packages/sundials)

**Comment by MichaelClerx** [comment]
> SUNLinSolFree and SUNMatDestroy could probably be called on exit to free memory of both objects.

Now have this in PR #169

**Comment by MichaelClerx** [comment]
Thanks @teosbpl !!
