### ISSUE TITLE
Allow components from other models to be imported

### ISSUE THREAD

**Issue by MichaelClerx** [MichaelClerx/myokit#665]
Proposed method `myokit.Model.import_component`:

```
def import_component(
        self, external_component, new_name=None, var_map=None, 
        allow_name_mapping=False, convert_units=False):
    """
    Imports a component from another model (the "source model") into this one 
    (the "target model").

    If variables in the ``external_component`` refer to variables from other 
    components they will be mapped on to variables from this model by trying
    the following strategies (in order):

    1. Using the provided dict ``var_map``, which maps variables in the source
       model to variables in this model.
    2. By assuming variables with the same label/binding map onto each other.
    3. By assuming that variables with the same qualified names map onto each
       other. This rule is only applied if ``allow_name_mapping`` is set to
       ``True``.

    Arguments:
    
    ``external_component``
        A :class:`myokit.Component` from another model.
    ``new_name``
        An optional new name for the imported component.
    ``var_map``
        An optional dict mapping variables from the source model to variables
        in this model (with variables specified as objects or as fully
        qualified names).
    ``allow_name_mapping``
        Set this to ``True`` to allow mapping based on fully qualified names,
        e.g. a variable ``x.y`` in the source model will be mapped to a
        variable ``x.y`` in the target model.
    ``convert_units``
        Set this to ``True`` to convert the units of any mapped variables, if
        required and possible.

    If any variables cannot be mapped, a :class:`myokit.WellNamedError`
    will be raised. Will raise a :class:`DuplicateNameError`(?) if the 
    components name or ``new_name`` clashes with an existing component name. If
    unit conversion is enabled and variables with incompattible units are
    mapped onto each other, a :class:`myokit.IncompatibleUnitsError` will be
    raised.    
    """
    
    # Check component is not from this model, is a component, etc.
    
    # Check if new name is provided, or else check that name doesn't clash
    
    # Create mapping for vars, and get unit conversion factors if required.
    
    # Clone contents of old component to new one
    # Not sure what the best strategy is. Re-write based on code from clone()?
    # Might need hidden methods in Component and in Variable.

    ...
```

**Comment by MichaelClerx** [comment]
Would this be enough, @Rebecca-Rumney @DavAug ?

**Comment by MichaelClerx** [comment]
(One tiny issue you'd have to deal with is user functions. Hardly ever used, but they exist! Basically you'd have to either copy the user function or (safer) rewrite it as an expression during the copying, probably just 3 lines + some tests)

**Comment by DavAug** [comment]
> Would this be enough, @Rebecca-Rumney @DavAug ?

I think this sounds really good!

I'm just rehashing what this is trying to do to understand this better:
- We want to import an external component into an existing model, for example to add a peripheral PK compartment to an existing PK model. E.g. an existing model
```
[[model]]
name: Linear, single-compartment PK model of drug distribution with bolus injection.
author: SABS:R3

# Initial values
central_compartment.drug = 0 [ng]

[central_compartment]
# bound variables (dosing controlled by the protocol, and time)
dose_rate = 0 [ng/h]
    in [ng/h]
    bind pace
    desc: Dose rate in ng/h. Controlled by protocol.
time = 0 [h]
    in [h]
    bind time
    desc: independent time variable in h.

# compartment internal parameters
CL = 2 [mL/h]
    in [mL/h]
    desc: Clearance/elimination rate from central compartment.
V = 4 [mL]
    in [mL]
    desc: Volume of central compartment.

# state variable
dot(drug) = dose_rate - drug * CL / V
    in [ng]
    desc: Drug in central compartment in ng.

# convert to concentration
drug_concentration = drug / V
    in [ng/mL]
    desc: Drug concentration in central compartment in ng/mL.

[[protocol]]
# Level  Start    Length   Period   Multiplier
2.0      2.0      0.5      6        0
```
and an external component from another file
```
[peripheral_compartment]
# compartment interal parameters
V = 2 [mL]
    in [mL]
    desc: Volume of peripheral compartment.
Kpc = 0 [1/h]
    in [1/h]
    desc: Transition rate from the peripheral compartment to the central compartment.

# compartment external parameters
use central_compartment.Kcp as Kcp

# state variable
dot(drug) = central_compartment.drug * Kcp - drug * Kpc
    in [ng]

# convert to concentration
drug_concentration = drug / V
    in [ng/mL]
    desc: Drug concentration in peripheral compartment in ng/mL.
```
become one new model:
```
[[model]]
name: Linear, single-compartment PK model of drug distribution with bolus injection.
author: SABS:R3

# Initial values
central_compartment.drug = 0 [ng]

[central_compartment]
# bound variables (dosing controlled by the protocol, and time)
dose_rate = 0 [ng/h]
    in [ng/h]
    bind pace
    desc: Dose rate in ng/h. Controlled by protocol.
time = 0 [h]
    in [h]
    bind time
    desc: independent time variable in h.

# compartment internal parameters
CL = 2 [mL/h]
    in [mL/h]
    desc: Clearance/elimination rate from central compartment.
V = 4 [mL]
    in [mL]
    desc: Volume of central compartment.

# state variable
dot(drug) = dose_rate - drug * CL / V
    in [ng]
    desc: Drug in central compartment in ng.

# convert to concentration
drug_concentration = drug / V
    in [ng/mL]
    desc: Drug concentration in central compartment in ng/mL.

[peripheral_compartment]
# compartment interal parameters
V = 2 [mL]
    in [mL]
    desc: Volume of peripheral compartment.
Kpc = 0 [1/h]
    in [1/h]
    desc: Transition rate from the peripheral compartment to the central compartment.

# compartment external parameters
use central_compartment.Kcp as Kcp

# state variable
dot(drug) = central_compartment.drug * Kcp - drug * Kpc
    in [ng]

# convert to concentration
drug_concentration = drug / V
    in [ng/mL]
    desc: Drug concentration in peripheral compartment in ng/mL.

[[protocol]]
# Level  Start    Length   Period   Multiplier
2.0      2.0      0.5      6        0
```
Here I just copy pasted the new component into the other model.

I think your suggested mapping takes care of the "loose" ends, by mapping the imports of the peripheral compartment to the correct variable in the central compartment. On thing that is missing is that the inflow / outflow in the rate expressions between the central and peripheral compartment are not added to the central compartment drug expression.

The correct expression for the central compartment would be 
```
# state variable
dot(drug) = dose_rate - drug * CL / V + drug * Kcp - peripheral.drug * peripheral.Kpc
    in [ng]
    desc: Drug in central compartment in ng.
``` 

And we can also see that this leaves the Kcp undefined (which was previously defined in the central compartment of the other model). So we maybe want to be able to have the option to take variable definition from the other model and add them to the imported model or something?

**Comment by Rebecca-Rumney** [comment]
So my aim is to have a PK model:

    [[Model]]
    [PK]
    dot(central) = ...
    dot(periferal) = ...

and PD model:

    [[Model]]
    [PlaceholderPK]
    conc = placeholder_function
    
    [PD]
    use PlaceholderPK.conc as conc
    dot(Effect) = f(conc)

to end up with a PKPD model:

    [[Model]]
    [PK]
    dot(central) = ...
    dot(periferal) = ...
    
    [PD]
    use PK.central as conc
    dot(Effect) = f(conc)`

or something similar to that effect.
I think what Micheal suggested should work for what I want it to do. But for yours David, you might need to use a separate function to add a little bit of text onto the dot(drug) line.

**Comment by MichaelClerx** [comment]
> On thing that is missing is that the inflow / outflow in the rate expressions between the central and peripheral compartment are not added to the central compartment drug expression.

Yeah, this part would be very application specific, so I'm guessing your PKPD code would have to deal with it
(E.g. with some lines like `drug = model.get('central_compartment.drug'); drug.set_rhs(myokit.Plus(drug.rhs(), ...))`)

In AP models a similar procedure might be

1. Import ion current component from other model
2. Update `i_ion` with terms for the new current, update `dot(species)` with the new current

As a second step we could think of adding some other construct to myokit to let you do this automatically.

For example, we might add some sort of `group` statement that lets you put variables in groups, and then have group functions e.g. `dot(drug) = sum(drug_group)`. But the consequences of such a step are much harder to see, so I'd start with the manual procedure for now?

**Comment by MichaelClerx** [comment]
> And we can also see that this leaves the Kcp undefined (which was previously defined in the central compartment of the other model). So we maybe want to be able to have the option to take variable definition from the other model and add them to the imported model or something?

In my proposal that would be an error unless you told the method where to get the new variable from, e.g. by first copying the variable and then adding either labels or providing a mapping `{'central_compartment.Kcp': 'new_compartment.Kcp'}`.

We could also consider some dirty `recursive` parameter in `import_component`, that will just keep grabbing unresolved variables and adding them locally, at the risk of importing the entire model!

**Comment by DavAug** [comment]
Ah ok coool! 

Yep I think your suggestion is really good then. I'd agree that the recursive thing of adding undefined variables is potentially not the best.

So where would this method be added btw? Will this be a method of the myokit.Model and it will take a .mmt file? Or are we thinking of having two myokit models, and then we get a myokit.Component from one Model and add it to the other?

**Comment by MichaelClerx** [comment]
> Or are we thinking of having two myokit models, and then we get a myokit.Component from one Model and add it to the other?

This one!

I understand you might want to have a toolbox of components that aren't necessarily in a model, but that would be much harder from Myokit's point of view! E.g. you'd have to be able to have a component with some kind of interface etc. But in the current code you can only create components after you've created a model! So I think it'd be easiest and still quite workable to have a toolbox of two-component models, e.g.

```
[[model]]
name: reusable-x-component
reusable_component.x = 1.234

[interface]
time = 0 [s]
  bind time   # This will help `import_component` find the variable
  in [s]           # This will help `import_component` check the units are compatible, and optionally convert?
t = 10
  label domain_specific_shared_variable   # This will help `import_component` map this variable

[reusable_component]
dot(x) = ...
  in [mV]
a = ...
b = ...
```

Then you could have a couple of these, and programmatically build a model, e.g.

```
main = myokit.parse_model('empty-model.mmt')
main.import_component(myokit.parse_model('reusable-x-component.mmt').get('reusable_component'), new_name='x')
main.import_component(myokit.parse_model('reusable-y-component.mmt').get('reusable_component'), new_name='y')
main.import_component(myokit.parse_model('reusable-z-component.mmt').get('reusable_component'), new_name='z')
main.get('shared_stuff.variable').set_rhs('x.x - y.y + z.z')
```

**Comment by DavAug** [comment]
Yep I’m actually quite happy with adding a component from one model to the other :)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MichaelClerx** [comment]
Cool! I've updated the proposal

**Comment by DavAug** [comment]
I can give it a go in a week time or so, I have to do some PKPDApp things first. Unless @Rebecca-Rumney is giving this a go?

**Comment by Rebecca-Rumney** [comment]
I could give it a go but I'd similarly won't be able to do it until about a week.

**Comment by MichaelClerx** [comment]
Cool! I've sent you an email so you can create a new branch and PR and such directly on this repo (instead of forking), if you like
