### ISSUE TITLE
Backward compatibility with XP 32, VS 2010, Anaconda 2.2.0, Sundials 2.7.0 may be achieved.

### ISSUE THREAD

**Issue by teosbpl** [MichaelClerx/myokit#68]
Backward compatibility with XP can be provided under a few simple conditions:
1. sundials is installed in standard location: C:\Program Files\sundials (not following its own instruction, but following its own defaults)
2. sundials_cvode.dll and sundials_nvecserial.dll are copied to C:\Windows\System32. Otherwise imp.load_dynamic(name, pathname) in _sim/__init__.py fails with notice "DLL load failed". Analyzed by stopping build qith pdb and checking myokit_sim_1.pyd with Dependency Walker.
3. All occurences of ESys_Flag flag variable declaration in sim/pacing.h are moved to the declaration (i.e. top of function body). As this is C file, it must copmly standard, otherwise VC 2010 fails to compile.
This would improve compliance.
4. Dependency on m.lib is removed from _sim/cvode.py line 119. Either this dependency is not required or it has to be satisfied some other way (looks like Linux specific  requirement for linking math library in GCC). Removing this line does not spoil script action. With this dependency in place, compilation fails on linker error that m.lib cannot be found.

**Comment by teosbpl** [comment]
Also dependency on Matplotlib 1.5.x  being the default can be relaxed to 1.4 with no noticeable side effects.

**Comment by MichaelClerx** [comment]
Thanks! Happy to make changes for XP as long as they can be made compatible with newer systems.

I think the only 1.5-specific feature Myokit currently uses is the prop_cycle key: https://matplotlib.org/users/prev_whats_new/whats_new_1.5.html#added-axes-prop-cycle-key-to-rcparams

**Comment by teosbpl** [comment]
May probably be safely closed. Matplotlib downgrade cannot be safely applied if 1.5 feature is used.

**Comment by MichaelClerx** [comment]
Just keeping this open until the final changes have been merged in :-)

**Comment by MichaelClerx** [comment]
Thanks!
