### ISSUE TITLE
SBML parser csymbol does not work

### ISSUE THREAD

**Issue by DavAug** [MichaelClerx/myokit#739]
Parsing an SBML file with csymbols fails, e.g.

```
<?xml version="1.0" encoding="UTF-8"?>
<sbml xmlns="http://www.sbml.org/sbml/level3/version2/core" level="3" version="2">
  <model id="antibiotic_linear_growth_hill_kill_resistance_model" timeUnits="second">

    <listOfParameters>
      <parameter id="bacterial_count" value="1" constant="false"/>
    </listOfParameters>

    <listOfRules>
      <assignmentRule variable="bacterial_count">
        <math xmlns="http://www.w3.org/1998/Math/MathML">
          <apply>
            <times/>
            <ci> bacterial_count </ci>
            <csymbol definitionURL="http://www.sbml.org/sbml/symbols/time"/>
          </apply>
        </math>
      </assignmentRule>
    </listOfRules>

  </model>
</sbml>
```

raises the following error

```
raise SBMLParsingError('Unable to parse rule: ' + str(e), element)
myokit.formats.sbml._parser.SBMLParsingError: Error on line 10. Unable to parse rule: Unable to parse MathML: Error on line 15. Unable to create Name from csymbol: Unknown or inaccessible symbol in MathML: "http://www.sbml.org/sbml/symbols/time".
```

**Comment by DavAug** [comment]
I checked the tests we wrote at the time and it seems that we only tested the SBML API for csymbols, but forgot to test the parser. 

It seems that the parser expects the csymbols already to be registered in the variable_factory, which is currently not the case. Would the best way to deal with this then to add supported csymbols to a global dictionary, such as the `assignable` dict in the parser @MichaelClerx ?

**Comment by MichaelClerx** [comment]
Good question!

You know more about this than me, but I suspect you might need to add a special variable to every sbml.Model to represent time, and then change the way that your `_add_time` method works when converting to a myokit.Model ?

(Related: looking back at the code now I was a little confused at the method _add_time, which doesn't change the sbml model but is used by the sbml-to-myokit conversion.Perhaps these methods should live in a separate class?)

**Comment by MichaelClerx** [comment]
Did we ever fix this @DavAug ?

**Comment by DavAug** [comment]
@MichaelClerx Nope, but it's definitely on my to do list. I might have a look this weekend :)

**Comment by MichaelClerx** [comment]
No rush, just curious!
