### ISSUE TITLE
SimulationOpenCL.set_connections() does not seem to work with precision=64

### ISSUE THREAD

**Issue by ThomasMBury** [MichaelClerx/myokit#743]
With precision=32, I am able to create arbitrary geometries in SimulationOpenCL using set_connections().

However, when I use precision=64, as has been required for some models, it seems to run without any connections i.e. no diffusion. No error messages appear.

I made a minimal working example attached below with 2 cells. Changing the precision from 32 to 64 breaks the diffusion between the two cells (at least for me!)
[mwe_test_connections.zip](https://github.com/MichaelClerx/myokit/files/6463417/mwe_test_connections.zip)

Any ideas @MichaelClerx?

**Comment by MichaelClerx** [comment]
Thanks @ThomasMBury , especially for the example! 

Which version of Myokit is this?
Can you copy-paste the output of `python3 -m myokit system` below ?

**Comment by ThomasMBury** [comment]
Sure, I was using the developer version:

WARNING:myokit:Using development version of Myokit (1.32.1.dev).
== System information ==
Myokit: 1.32.1.dev
Python: 3.9.4 (default, Apr  9 2021, 09:32:38) 
        [Clang 10.0.0 ]
OS: Darwin (darwin, posix)

== Python requirements ==
NumPy: 1.20.1
SciPy: 1.6.3
Matplotlib: 3.4.2
ConfigParser: OK
Setuptools: 52.0.0.post20210125

== Python extras ==
SymPy: Not found
CMAES: Not found
MoviePy: Not found

== GUI ==
PyQt5: 5.9.7
  Sip: OK
PyQt4: Not found
PySide: Not found
PySide2: Not found

== Development tools ==
Sphinx: 3.5.3
Flake8: 3.9.0

== Simulation tools ==
Compiler: Clang (Apple LLVM) 12.0.0
Sundials: 5.6.1
OpenCL: 2 device(s) found
  Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz on Apple
  Intel(R) Iris(TM) Plus Graphics 645 on Apple
  Use `python -m myokit opencl` for more information.

= /Users/tbury/.config/myokit/myokit.ini =
[myokit]
# This file can be used to set global configuration options for Myokit.

[time]
# Date format used throughout Myokit
# Format should be acceptable for time.strftime
date_format = %Y-%m-%d %H:%M:%S
# Time format used throughout Myokit
time_format = %H:%M:%S

[debug]
# Add line numbers to debug output of simulations
line_numbers = True

[gui]
# Backend to use for graphical user interface.
# Valid options are "pyqt5", "pyqt4" or "pyside".
# Leave unset for automatic selection.
#backend = pyqt5
#backend = pyqt4
#backend = pyside

[sundials]
# Location of sundials shared libary files (.so or .dll).
# Multiple paths can be set using ; as separator.
lib = /usr/local/lib;/opt/local/lib;/usr/local/Cellar/
# Location of sundials header files (.h).
inc = /usr/local/include;/opt/local/include;/usr/local/Cellar/
version = 50601

[opencl]
# Location of opencl shared libary files (.so or .dll).
# Multiple paths can be set using ; as separator.
lib = /usr/lib64
#;/usr/lib64/nvidia;/usr/local/cuda/lib64;/System/Library/Frameworks
# Location of opencl header files (.h).
inc = /usr/include/CL
#;/usr/local/cuda/include;/System/Library/Frameworks

**Comment by MichaelClerx** [comment]
OK that rules out my first guess ( https://github.com/MichaelClerx/myokit/pull/741 )

Thanks for reporting. Will try to have a look at this before the end of the week

**Comment by ThomasMBury** [comment]
Great, thank you. Let me know if there's anything I can do to help debug.

**Comment by MichaelClerx** [comment]
Adapted the minimum example you sent (thanks!)
I see it too!

```
#!/usr/bin/env python3
# Minimum working example to test set_connections.
import matplotlib.pyplot as plt
import myokit
import numpy as np

# Get model and protocol
m = myokit.load_model('br-1977.mmt')

# Make protocol
bcl = 1000
duration = 10
p = myokit.pacing.blocktrain(bcl, duration)

# Run simulations
s1 = myokit.SimulationOpenCL(m, p, ncells=2, precision=myokit.SINGLE_PRECISION)
s1.set_conductance(1)
s1.set_connections([(0, 1, 1)])
s1.set_paced_cells(1)
d1 = s1.run(40)

s2 = myokit.SimulationOpenCL(m, p, ncells=2, precision=myokit.DOUBLE_PRECISION)
s2.set_conductance(1)
s2.set_connections([(0, 1, 1)])
s2.set_paced_cells(1)
d2 = s2.run(40)

# Display the result
f = plt.figure()
x = f.add_subplot(1, 2, 1)
x.plot(d1['engine.time'], d1['membrane.V', 0])
x.plot(d1['engine.time'], d1['membrane.V', 1])
x = f.add_subplot(1, 2, 2)
x.plot(d2['engine.time'], d2['membrane.V', 0])
x.plot(d2['engine.time'], d2['membrane.V', 1])
f.savefig('out.png')
```

**Comment by MichaelClerx** [comment]
Hmmmmm
```
#!/usr/bin/env python3
# Minimum working example to test set_connections.
import myokit

# Get model and protocol
m = myokit.load_model('br-1977.mmt')

# Make protocol
bcl = 1000
duration = 10
p = myokit.pacing.blocktrain(bcl, duration, level=1)

# Run simulations
s1 = myokit.SimulationOpenCL(m, p, ncells=2, precision=myokit.SINGLE_PRECISION)
s1.set_paced_cells(1)
s2 = myokit.SimulationOpenCL(m, p, ncells=2, precision=myokit.DOUBLE_PRECISION)
s2.set_paced_cells(1)
g = 1
t = 20

s1.set_conductance(g)
d1a = s1.run(t)
x1a = max(d1a['membrane.V', 1]) > 0
print(x1a)

s1.reset()
s1.set_connections([(0, 1, g)])
d1b = s1.run(t)
x1b = max(d1b['membrane.V', 1]) > 0
print(x1b)

s2.set_conductance(g)
d2a = s2.run(t)
x2a = max(d2a['membrane.V', 1]) > 0
print(x2a)

s2.reset()
s2.set_connections([(0, 1, g)])
d2b = s2.run(t)
x2b = max(d2b['membrane.V', 1]) > 0
print(x2b)

# Display the result
import matplotlib.pyplot as plt
f = plt.figure(figsize=(10, 8))
f.subplots_adjust(0.1, 0.1, 0.98, 0.95, 0.3, 0.3)
x = f.add_subplot(2, 2, 1)
x.set_title('set_conductance, sp')
x.plot(d1a['engine.time'], d1a['membrane.V', 0])
x.plot(d1a['engine.time'], d1a['membrane.V', 1])
x = f.add_subplot(2, 2, 2)
x.set_title('set_connections, sp')
x.set_ylabel('Vm')
x.plot(d1b['engine.time'], d1b['membrane.V', 0])
x.plot(d1b['engine.time'], d1b['membrane.V', 1])
x = f.add_subplot(2, 2, 3)
x.set_title('set_conductance, dp')
x.set_xlabel('Time')
x.set_ylabel('Vm')
x.plot(d2a['engine.time'], d2a['membrane.V', 0])
x.plot(d2a['engine.time'], d2a['membrane.V', 1])
x = f.add_subplot(2, 2, 4)
x.set_xlabel('Time')
x.set_title('set_connections, dp')
x.plot(d2b['engine.time'], d2b['membrane.V', 0])
x.plot(d2b['engine.time'], d2b['membrane.V', 1])
f.savefig('out.png')
```

**Comment by MichaelClerx** [comment]
Expanded plot:

```
#!/usr/bin/env python3
# Minimum working example to test set_connections.
import myokit

# Get model and protocol
m = myokit.load_model('br-1977.mmt')

# Make protocol
bcl = 1000
duration = 10
p = myokit.pacing.blocktrain(bcl, duration, level=1)

# Run simulations
s1 = myokit.SimulationOpenCL(m, p, ncells=2, precision=myokit.SINGLE_PRECISION)
s1.set_paced_cells(1)
s2 = myokit.SimulationOpenCL(m, p, ncells=2, precision=myokit.DOUBLE_PRECISION)
s2.set_paced_cells(1)
g = 1
t = 11

s1.set_conductance(g)
d1a = s1.run(t, log_interval=0.1)
x1a = max(d1a['membrane.V', 1]) > 0
print(x1a)

s1.reset()
s1.set_connections([(0, 1, g)])
d1b = s1.run(t, log_interval=0.1)
x1b = max(d1b['membrane.V', 1]) > 0
print(x1b)

s2.set_conductance(g)
d2a = s2.run(t, log_interval=0.1)
x2a = max(d2a['membrane.V', 1]) > 0
print(x2a)

s2.reset()
s2.set_connections([(0, 1, g)])
d2b = s2.run(t, log_interval=0.1)
x2b = max(d2b['membrane.V', 1]) > 0
print(x2b)

# Display the result
import matplotlib.pyplot as plt
f = plt.figure(figsize=(10, 10))
f.subplots_adjust(0.08, 0.07, 0.98, 0.95, 0.2, 0.4)

x = f.add_subplot(4, 2, 1)
x.set_title('set_conductance, sp')
x.set_ylabel('Vm')
x.plot(d1a['engine.time'], d1a['membrane.V', 0])
x.plot(d1a['engine.time'], d1a['membrane.V', 1])
x = f.add_subplot(4, 2, 2)
x.set_title('set_connections, sp')
x.set_ylabel('Vm')
x.plot(d1b['engine.time'], d1b['membrane.V', 0])
x.plot(d1b['engine.time'], d1b['membrane.V', 1])

x = f.add_subplot(4, 2, 3)
x.set_ylabel('I_diff')
x.plot(d1a['engine.time'], d1a['membrane.i_diff', 0])
x.plot(d1a['engine.time'], d1a['membrane.i_diff', 1])
x = f.add_subplot(4, 2, 4)
x.set_ylabel('I_diff')
x.plot(d1b['engine.time'], d1b['membrane.i_diff', 0])
x.plot(d1b['engine.time'], d1b['membrane.i_diff', 1])

x = f.add_subplot(4, 2, 5)
x.set_title('set_conductance, dp')
x.set_ylabel('Vm')
x.plot(d2a['engine.time'], d2a['membrane.V', 0])
x.plot(d2a['engine.time'], d2a['membrane.V', 1])
x = f.add_subplot(4, 2, 6)
x.set_ylabel('Vm')
x.set_title('set_connections, dp')
x.plot(d2b['engine.time'], d2b['membrane.V', 0])
x.plot(d2b['engine.time'], d2b['membrane.V', 1])

x = f.add_subplot(4, 2, 7)
x.set_xlabel('Time')
x.set_ylabel('I_diff')
x.plot(d2a['engine.time'], d2a['membrane.i_diff', 0])
x.plot(d2a['engine.time'], d2a['membrane.i_diff', 1])
x = f.add_subplot(4, 2, 8)
x.set_ylabel('I_diff')
x.set_xlabel('Time')
x.plot(d2b['engine.time'], d2b['membrane.i_diff', 0])
x.plot(d2b['engine.time'], d2b['membrane.i_diff', 1])

f.savefig('out.png')
```

![out](https://user-images.githubusercontent.com/517644/118272497-9f08c180-b4ba-11eb-9201-65ceeeec7a50.png)

**Comment by MichaelClerx** [comment]
Appears to be something to do with the atomic adding operation to calculate full idiff. No idea why that's different for double precision yet

**Comment by MichaelClerx** [comment]
OK, the atomic add operation relies on casting a Real (single or double) to an int, and then performing an atomic comparison:

- https://simpleopencl.blogspot.com/2013/05/atomic-operations-and-floats-in-opencl.html
- https://www.khronos.org/registry/OpenCL/sdk/1.2/docs/man/xhtml/atomic_cmpxchg.html

So we need to use a different data type for the int, and a slightly different function call (plus a pragma) for the full precision case...

**Comment by MichaelClerx** [comment]
@ThomasMBury I've uploaded a fix, but it requires an OpenCL extension that's not always available. To minimise the impact of enabling this extension, I might have to add a construction-time parameter that says "i want to use connections", so some work still left to do.

Before I do that though, could you try out the fix in this branch https://github.com/MichaelClerx/myokit/pull/744 on your machine?

**Comment by ThomasMBury** [comment]
Yes this branch is working! Thanks so much.

**Comment by MichaelClerx** [comment]
The latest code in `main` has an updated fix for this issue.
