### ISSUE TITLE
Recent changes in LoggedVariableInfo prohibit logging constants

### ISSUE THREAD

**Issue by teosbpl** [MichaelClerx/myokit#75]
Prior to recent changes it was possible to log variables like
s.run(35, log=['potassium.i','sodium.i']) in line with 'membrane.V'
Either a snippet should be published for achieving this functionality within current code version or an option to log these variables should be reintroduced.
This limits possibility to study all variables of a single model.
From point of view of a model like HH sodium.i and potassium.i are not constants, so there may be some flaw in package logic.

**Comment by MichaelClerx** [comment]
This should definitely be possible! Could you send me an example so I can debug this?

**Comment by teosbpl** [comment]
m, p, x = myokit.load('hh-1952d-modern.mmt')
#m, p, x = myokit.load('hh_model.mmt')

p1 = myokit.parse_protocol("""[[protocol]]
# Level  Start    Length   Period   Multiplier
1.0      5        0.05     30     0
+50.0      5.05        0.05     30     0
+40.0      5.10        20     30     0
""")
# Create simulation
#m = get_model()
#p = get_protocol()
s = myokit.Simulation(m, p1)

# Selected variables
t = 'engine.time'
v = 'membrane.V'
iK = 'potassium.i'
n = 'potassium.n'
m = 'sodium.m'
iNa = 'sodium.i'
h = 'sodium.h'

# Run simulation
[hh-1952d-modern.mmt.txt](https://github.com/MichaelClerx/myokit/files/1804949/hh-1952d-modern.mmt.txt)

d = s.run(35, log=[t, v,n,m,h,iNa,iK])

**Comment by MichaelClerx** [comment]
Hmmm. This works fine for me! Are you testing with Python3?

**Comment by MichaelClerx** [comment]
Here's an example that runs without errors for me:

[[model]]
    name: HodgkinHuxley1952d_Modern
    desc: """
        Myokit implementation of the model described in Hodgkin and Huxley's 1952
        paper [1], updated to use modern conventions.

        The modernization consisted of mirroring the gate functions around the
        point V=-75 to obtain the usual direction of depolarization. Additionally,
        the formulation V = E - Er was dropped and V is taken to be the action
        potential, not the difference in action potential.
        
        [1] A quantitative description of membrane current and its application to
        conduction and excitation in nerve.
        Hodgkin, Huxley, 1952d, Journal of Physiology
        """
    author: Michael Clerx
    # Initial values
    #membrane.V  = -75.0
    potassium.n = 0.317
    sodium.m    = 0.05
    sodium.h    = 0.595

    [engine]
    time = 0 bind time
    pace = 0 bind pace

    #
    # Membrane potential
    #
    [membrane]
    #dot(V) = if(engine.pace > 0,
    #        (Vhold - V) * 100,
    #        -(1/C) * (sodium.i + potassium.i + leak.i))
    #    in [mV]
    #    desc: The membrane potential
    V = engine.pace
    C = 1 [uF/cm^2] : The membrane capacity per unit area (See table 3 in HH1952d)
    Vhold = -60 [mV] : A temporary holding potential

    #
    # Potassium current
    #
    [potassium]
    use membrane.V
    Ek = -87 [mV]
    g_max = 36 [mS/cm^2]
    i = g_max * n^4 * (V - Ek)
        desc: Current carried by potassium ions
        in [uA/cm^2]
    dot(n) = a * (1 - n) - b * n
        a = 0.01 * (-V - 65) / (exp((-V - 65) / 10) - 1)
        b = 0.125 * exp((-V - 75) / 80)

    #
    # Sodium current
    #
    [sodium]
    use membrane.V
    ENa = 40 [mV]
    g_max = 120 [mS/cm^2]
    i = g_max * m^3 * h * (V - ENa)
        desc: Current carried by Sodium ions
        in [uA/cm^2]
    dot(m) = a * (1 - m) - b * m
        a = 0.1 * (-V - 50) / (exp((-V - 50) / 10) - 1)
        b = 4 * exp((-V - 75) / 18)
    dot(h) = a * (1 - h) - b * h
        a = 0.07 * exp((-V - 75) / 20)
        b = 1 / (exp((-V - 45) / 10) + 1)

    #
    # Leak current
    #
    [leak]
    use membrane.V
    Eleak = -64.387
    g_max = 0.3 [mS/cm^2]
    Istim = 0.0 # -6.0
    i = Istim + g_max * (V - Eleak)

    [[protocol]]
    # Level  Start    Length   Period   Multiplier
    1.0      5        0.05     30     0
    +50.0      5.05        0.05     30     0
    +40.0      5.10        20     30     0

    [[script]]
    import matplotlib.pyplot as pl
    import myokit

    # Create simulation
    m = get_model()
    p = get_protocol()
    s = myokit.Simulation(m, p)

    # Selected variables
    t = 'engine.time'
    v = 'membrane.V'
    iK = 'potassium.i'
    n = 'potassium.n'
    m = 'sodium.m'
    iNa = 'sodium.i'
    h = 'sodium.h'

    # Run simulation
    d = s.run(35, log=[t, v,n,m,h,iNa,iK])

**Comment by teosbpl** [comment]
You are right,
problem is in my recent changes in _expr.py which must have affected the references. The issue is closed.

**Comment by teosbpl** [comment]
Hi Michael,
There is definitely an issue in my code: during model build-up variables such as 'sodium.i' are treated as constants and not as state variables.
I managed to code absolute imports and many useful changes with Python2to3 compatibility, but if you have a clue concerning what could possibly go wrong, before I find some time to sit to this code, I'd be obliged.
Details can be found here:
https://github.com/MichaelClerx/myokit/compare/master...teosbpl:feature/Python3compatibilityIssues

**Comment by MichaelClerx** [comment]
Thanks for working on this! I'll have a look soon!

**Comment by teosbpl** [comment]
BTW: Python2; nothing to thank for yet :-/
