### ISSUE TITLE
OpenCL extension cl_khr_fp64 does not exist on macOS Big Sur 11.4

### ISSUE THREAD

**Issue by ThomasMBury** [MichaelClerx/myokit#771]
Hi Michael,

The OpenCL extensions required for double precision simulations don't exist on my Mac (Macbook Pro), so running myokit.SimulationOpenCL with precision=64 runs into the following error now

`Exception: The OpenCL extension cl_khr_fp64 is required for double precision simulations, but was not found on the current OpenCL platform/device.
`

What's strange is that when you made the original fix to Issue #743, I was able to run the double precision simulations without this extension. I'm currently running the double precision simulations just fine with the developer version at commit 13fabd75113d26f35083c3564b801154e2736562 on May 18, but any commit after that runs into the issue of requiring the extension.

Is there a way to make it possible to run the double precision simulations without the extension cl_khr_fp64?

Cheers,
Tom

**Comment by MichaelClerx** [comment]
Hi Tom,
That's pretty interesting!
It sounds like the driver might be reporting its capabilities incorrectly, which would be a bit of a nuisance if that's really the case.

Could you try two things for me?

1. Use `python -m myokit opencl-select` to switch between a user-selected device and automatic selection. Just to check that we get the same results for both.
2. Comment out these lines in `openclsim.c`: https://github.com/MichaelClerx/myokit/blob/main/myokit/_sim/openclsim.c#L704-L714

If commenting out the check fixes the issue, I think I will just turn it from an exception into a warning. Then you'd still get a warning saying "cl_khr_fp64 support is not reported" or something along those lines, but it would then just run anyway...

**Comment by ThomasMBury** [comment]
Sure! My `python -m myokit opencl-select` returns



```
WARNING:myokit:Using development version of Myokit (1.32.1.dev).
======================================================================
Myokit OpenCL device selection
======================================================================
Selected platform: No preference
Selected device  : No preference
======================================================================
Available devices:
----------------------------------------------------------------------
(1) Select automatically.
----------------------------------------------------------------------
(2) Platform: Apple
    Device: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    1.4000000000000001 GHz, 8.0 GB global, 32.0 KB local, 64.0 KB const
----------------------------------------------------------------------
(3) Platform: Apple
    Device: Intel(R) Iris(TM) Plus Graphics 645
    1.0 GHz, 1.5 GB global, 64.0 KB local, 64.0 KB const
----------------------------------------------------------------------
```

When I try options 1, 2 and 3 I get the same exception
```
Exception: The OpenCL extension cl_khr_fp64 is required for double precision simulations, but was not found on the current OpenCL platform/device.
```

When I comment out the lines in `openclsim.c` the simulation runs! I've confirmed that the diffusion is also working in this simulation. Turning the exception into a warning sounds good to me, thanks.
