### ISSUE TITLE
Stimulus protocol with varying location?

### ISSUE THREAD

**Issue by ThomasMBury** [MichaelClerx/myokit#778]
Hi Michael,
General question here. Is it possible to create a stimulus protocol such that the location of the stimulus varies over time?
Specifically, I would like to stimulate a tissue in one location at one time, and then in a different location at a later time.
Let me know.
Cheers,
Tom

**Comment by MichaelClerx** [comment]
Hi @ThomasMBury ,
Usually I'd do that by just stopping the simulation and changing the settings, e.g.
```
log = s.run(1000)
s.set_paced_cells(...)
log = s.run(1000, log=log)
```
If you're needing something more clever (e.g gradual continuous change) I guess you could do that by multiplying with some function of a spatially varying scalar, e.g., in your model you'd have
```
[stimulus]
pacing = 0 bind pace
x = 0
I_stim = f(pacing, x)
```
and then
```
x = np.zeros(ny, nx)
x = ...
s.set_field('stimulus.x', x)
```

**Comment by ThomasMBury** [comment]
This works well, thanks!
