### ISSUE TITLE
Unpickling myokit.Name failed

### ISSUE THREAD

**Issue by dkabus** [MichaelClerx/myokit#842]
To use Myokit with the [multiprocessing module](https://docs.python.org/3/library/multiprocessing.html), I need to pass `myokit.Name` objects between processes. This is done by [pickling](https://docs.python.org/3/library/pickle.html) and unpickling that object. When unpickling the object, I get an error that can easily be reproduced with this code:
```py
import myokit
import pickle
name = myokit.Name(42.0)
pickled_name = pickle.dumps(name)
unpickled_name = pickle.loads(pickled_name)
```

Full error mesage:
```py
AttributeError                            Traceback (most recent call last)
Input In [5], in <module>
----> 1 pickle.loads(pickle.dumps(myokit.Name(42.0)))

File ~/.local/lib/python3.10/site-packages/myokit/_expressions.py:502, in Expression.__hash__(self)
    501 def __hash__(self):
--> 502     if self._cached_hash is None:
    503         self._cached_hash = hash(self._polish())
    504     return self._cached_hash

AttributeError: 'Name' object has no attribute '_cached_hash'
```

Again, thanks for actively maintaining this module! Very much appreciated.

Platform: Arch Linux, Python 3.10.1, Myokit 1.33.1

**Comment by MichaelClerx** [comment]
Hi @dkabus , thanks for the very clear bug report and the example code!
Will fix as soon as possible.

Myokit was not designed with pickling/unpickling in mind, so you may run into more of these issues. I did add pickling for models, protocols, and (CVODE) simulations. But note that unpickling a simulation involves a compilation step, so things won't be fast if you do that a lot.

I'm slightly curious that you're seeing this on arch linux though, as the [default start method for multiprocessing there is `fork`](https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods), which [doesn't require pickling](https://docs.python.org/3/library/multiprocessing.html#all-start-methods) ?

**Comment by dkabus** [comment]
Okay, thanks!

I am using a [parallelised implementation of the L-BFGS-B optimiser](https://pypi.org/project/optimparallel/) which apparently uses multiprocessing and/or pickling regardless of OS its running on. Once the objects are unpickled in the child processes, only floats are exchanged between the processes and no more compilation is necessary.

**Comment by MichaelClerx** [comment]
Cool!

Would a workaround be to just use string names instead of Name objects?

I'm asking because I'm struggling a bit to think how best to solve this one. It's quite easy to serialise Name objects (and expressions in general) because they already have a string representation (their mmt code). The problem is that names have links to variables, and those links would be lost if you do it this way. The alternative - also pickling the full model - is even worse.

**Comment by dkabus** [comment]
Yes, that is exactly how I solved that issue in my code once I figured out that pickling was the problem. In my opinion it might be sufficient to throw a helpful error message...?

**Comment by MichaelClerx** [comment]
This sent me down a bit of a rabbit hole of checking how I'd implemented equality checks, hashing, and pickling over the years...

If you did want to serialise expressions, you could use the following approach:

```
import myokit
import pickle

# Load a model
model = myokit.load_model('example')

# Get an expression containing Names
expression = model.get('ina.INa').rhs()
print(expression, type(expression))

# To serialise, get a string representation of the expression (no longer linked to a model)
string = expression.code()

pickled_string = pickle.dumps(string)
unpickled_string = pickle.loads(pickled_string)

print(unpickled_string, type(unpickled_string))

# After unpickling, create a new expression from the string (using the model as "context")
new_expression = myokit.parse_expression(unpickled_string, context=model)
print(new_expression, type(new_expression))
```

And this is now hinted at in the error message you will now get when trying to pickle any expression (including names):
```
>>> pickle.dumps(expression)

NotImplementedError: Individual myokit Expressions can not be pickled. Please try e.g. pickling a full model,
or pickling the output of `Expression.code()` and following unpickling with a call to 
`myokit.parse_expression(unpickled_code, context=a_model)` to recreate the Expression.
```
