### ISSUE TITLE
Minor memory leak when simulating with protocol

### ISSUE THREAD

**Issue by DavAug** [MichaelClerx/myokit#855]
I have been profiling the memory usage of my inference model and noticed that each `myokit.Simulation.run()` call creates a list. These lists do not seem to be picked up by Python's garbage collector (but I am definitely no expert on this).

Here is a code snippet to reproduce the results:
```
import myokit
from pympler import muppy, summary

m, p, x = myokit.load('example')
s = myokit.Simulation(m, p)

for _ in range(100):
    s.run(1000)
    summary.print_(summary.summarize(muppy.get_objects()))
```

On my machine I can see that the number of lists grows with each call of `s.run(1000)`, e.g.:

```
                       types |   # objects |   total size
============================ | =========== | ============
                        list |        9892 |      1.27 MB

                       types |   # objects |   total size
============================ | =========== | ============
                        list |        9893 |      1.27 MB

                       types |   # objects |   total size
============================ | =========== | ============
                        list |        9894 |      1.27 MB
```

Note that this does not happen when no protocol is set. 

I only noticed it because this list creation accumulates for hierarchical models when you have to solve the model many times. 

Do you have an idea what might cause this?

**Comment by MichaelClerx** [comment]
Great find, and a very useful approach!

I've added a fix for this one in https://github.com/MichaelClerx/myokit/pull/857

**Comment by MichaelClerx** [comment]
I would not be surprised if there are others. Will have to look into that some time 😅
