### ISSUE TITLE
using `import_component` and mapping internal variable to another component

### ISSUE THREAD

**Issue by martinjrobins** [MichaelClerx/myokit#877]
I'm having problems with `import_component` again :(. Say I have this model:

```
[myokit]
drug_concentration = 1
dot(tumour_volume) = 2 * drug_concentration
```

and I want to import it into the model below, but I want to map `{myokit.drug_concentration: central.drug_c_concentration}`. 

```
[central]
dot(drug_c_concentration) = 2
```

so the final model should be something like:

```
[myokit]
use central.drug_c_concentration as drug_concentration
dot(tumour_volume) = 2 * drug_concentration

[central]
dot(drug_c_concentration) = 2
```

However, the docstring on `import_component` seems to imply that I can't do this with `var_map`, since drug_concentration does not refer to an external variable, but ratheran internal one to the component. And I've tried it in practice and it doesn't work. 

What is the best way to achieve what I'm trying to do?

**Comment by MichaelClerx** [comment]
Import it first, and then do `model.get('myokit.drug_concentation').set_rhs('central.drug_c_concentration)` ?

**Comment by MichaelClerx** [comment]
Or you could go for a
```
v = model.get('myokit.tumour_volume')
v.set_rhs(v.rhs().clone(subst={'myokit.drug_concentration': 'central.drug_c_concentration'})
model.get('myokit').remove_variable(model.get('myokit.drug_concentration'))
```
?

**Comment by MichaelClerx** [comment]
I don't think the import component function should be made to handle this case

**Comment by martinjrobins** [comment]
no, I don't think so either. Thanks, I'll try one of those methods, thanks!
